[package]
name = "prisma"
version = "0.1.0"
edition = "2021"

[dependencies]
prisma-client-rust = { workspace = true, features = ["sqlite", "migrations"] }
prisma-client-rust-cli = { workspace = true, features = [
    "sqlite",
    "migrations",
] }
